# Generated by Django 5.0.6 on 2024-08-22 15:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('added_on', models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 22, 15, 24, 57, 97771, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime(2024, 8, 22, 15, 24, 57, 98344, tzinfo=datetime.timezone.utc))),
                ('user', models.CharField(max_length=1000)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChatApp.room')),
            ],
        ),
    ]
